### ISSUE TITLE
(Automated) Transformation of RDF datasets into CSV format for datamining input

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#14]
In order to provide the Input for datamining in a usable Format, we Need to transform our RDF datasets into the required CSV Format. At best this can be automated.
We Need to:
- agree on a CSV Format which is usable for datamining (provided by the datamining people)
- find a way to transform the RDF-datasets to this CSV-Format (done by LinkedPipes)
- automate this Transformation on our Server (being triggered whenever new RDF-datasets are added to our server)

**Comment by jindrichmynarz** [comment]
First, we need to know what is required by the data mining, so that we know what we need to solve.

We already have a [pipeline fragment that converts a **single** Data Cube Vocabulary dataset into CSV](https://github.com/openbudgets/pipeline-fragments/tree/master/dcv/dcv-to-csv). It produces a CSV based on the data structure definition of the dataset.

We also discussed a possibility to create a RDF2FDP pipeline, an inverse of the [FDP2RDF pipeline](https://github.com/openbudgets/pipeline-fragments/tree/master/FDPtoRDF), after @marek-dudas finishes the FDP2RDF pipeline. Such pipeline would need to be generic, so it's likely it will reuse the DCV to CSV pipeline, and thus suffer from the same limitations.

However, while these pipelines support a **single** dataset, it is likely that data mining would require to join **multiple** datasets into a CSV. The data mining input would be then created as a custom _view_ over multiple datasets. Moreover, while the combined datasets may be represented using the [OpenBudgets.eu data model](https://github.com/openbudgets/data-model), we may also need to combine other datasets that may not even be modelled using the Data Cube Vocabulary, such as contextual data on demographics or politics. Instead of generic views, we would need custom ones when combining heterogeneous datasets.

We can write SPARQL `SELECT` queries to produce custom views over multiple datasets that output a single CSV table required by the data mining tools. It doesn't get much simpler than that. UIs for query builders can be simpler only if we constrain the types of views they can generate.

IMHO, developing UIs for feature selection would be a bit premature at this point. At this stage, we do one-off data mining experiments to see what's viable. Once we determine what data mining functionality can by interesting to the users and feasible to implement we can better formulate what data it requires and consequently prepare UIs for preparing the data.

**Comment by ChristianeEngels** [comment]
> First, we need to know what is required by the data mining, so that we know what we need to solve.

I've added this requirement analysis to the agenda of tomorrow's data mining/analytics call.
As I already wrote down there I'd have the following functionality in mind for a possible future pipeline:
- Combine multiple data sets (Caution: dimensions might have to be matched here, e.g. `<http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2014/dimension/economicClassification>` and  `<http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2015/dimension/economicClassification>`)
- Filter the observations
- Select (relevant) features (and implicitly perform aggregation to get unique observations)
- Get the labels/notations instead of URIs (i.e. 2014 instead of `<http://reference.data.gov.uk/id/year/2014>`)

I agree with @jindrichmynarz that we can go for SPARQL SELECT queries to create the custom CSVs for now.

**Comment by jindrichmynarz** [comment]
Some thoughts on the points you made:

> Combine multiple data sets (Caution: dimensions might have to be matched here, e.g. `<http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2014/dimension/economicClassification>` and `<http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2015/dimension/economicClassification>`)

If component properties are interchangeable, it should be explicitly asserted using `owl:equivalentProperty`. Linking component properties (as done in [D1.8](http://openbudgets.eu/assets/deliverables/D1.8.pdf)) is orthogonal to generating view of data for data mining. However, the component properties in various datasets are interchangeable, ETL developers in the context of OpenBudgets.eu should use the same component property. It would be great to have think about this with concrete examples, such as why we have both `<http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2014/dimension/economicClassification>` and `<http://data.openbudgets.eu/ontology/dsd/aragon-budget-inc-2015/dimension/economicClassification>` instead of a single property.

> Filter the observations

This is basically a generic graph pattern. It would be better to restrict this further (e.g., numeric filters on amounts). Otherwise, we would be developing a generic SPARQL query builder UI.

> Select (relevant) features (and implicitly perform aggregation to get unique observations)

Observations are uniquely identified by their IRIs. Why would you need to merge different observations sharing the same values for the few selected features?

> Get the labels/notations instead of URIs (i.e. 2014 instead of http://reference.data.gov.uk/id/year/2014)

I already discussed this with @jaroslav-kuchar a few months ago. He told me that in data mining it doesn't matter whether you have `<http://reference.data.gov.uk/id/year/2014>` or `2014`. In fact, having the IRI may be better because it can provide you with more data. We discussed that using notations or labels instead of IRIs is a matter of **presentation** of data mining results. Therefore, I think this is a WP3's concern.

The only situation I can think of in which you may want labels instead of IRIs in data mining is when you apply natural language processing. However, I'm not aware of any plans to use NLP in OpenBudgets.eu. Perhaps you have another use case on mind that I overlooked.

**Comment by schmaluk** [comment]
@jaroslav-kuchar @vojir @jindrichmynarz @HimmelStein Should the Datamining algorithms produce the CSV files they work on themselves or should they be passively invoked by DAM https://github.com/openbudgets/DAM expecting their different desired CSV formats? If we go for the first case, it might be good at least to externalize the selection of the datasets (muncipality, year). So not every datamining algorithm has to re-implement this Feature as noted by @ChristianeEngels

**Comment by jindrichmynarz** [comment]
I think @vojir said he prefers the push approach: input data for data mining is pushed to them via DAM.

**Comment by schmaluk** [comment]
As discussed today in the Meeting we postpone this item for being integrated after the prototype. So the DM algorithm developers have more time to define the proper Input data for their algorithms and how the Input data should get produced (for example by a datamining frontend or by using LinkedPipes pipelines)

**Comment by pwalsh** [comment]
@badmotor I'm closing this. It must be out of date, and any specific issues can be raised with distinct issues.
