### ISSUE TITLE
Transferring data between triplestores (staging -> production)

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#6]
Once the fdp-data has been transformed and uploaded to the staging triplestore, the data in the staging triplestore Need to be possibly enhanced/modified and afterwards transferred to the production triplestore.

**Please extend the Pipeline in LinkedPipes in order to Transfer the data from the staging triplestore to the production triplestore**.

If you have alternative suggestions how to get the data transferred between the triplestores, please lets discuss it here.

**Comment by jindrichmynarz** [comment]
Here's my thinking out loud.

I think the synchronization pipeline would mostly require changes in our workflow when producing data instead of changes in LP-ETL.

The main question to answer when implementing the synchronization pipeline is what data should be synchronized. This includes the decisions if we should push only a subset of data to the production RDF store and how to determine which data changed and thus needs to be updated.

In order to simplify the problem, we can start by ignoring both these decisions and instead synchronize all data in bulk.

At first glance, it seems this pipeline could be as simple as loading all data from the staging store via [e-sparqlEndpoint](https://github.com/linkedpipes/etl/tree/master/plugins/e-sparqlEndpoint) (or simply [e-httpGet](https://github.com/linkedpipes/etl/tree/master/plugins/e-httpGetFile) using the SPARQL Graph Store protocol) and then pushing the data to the production store via [l-graphStoreProtocol](https://github.com/linkedpipes/etl/tree/master/plugins/l-graphStoreProtocol). However, e-sparqlEndpoint's `CONSTRUCT` queries allow only to create triples, not quads, so the distinction between named graphs is lost.

An alternative could be to obtain a list of all named graphs via [t-sparqlSelect](https://github.com/linkedpipes/etl/tree/master/plugins/t-sparqlSelect), then generate a CONSTRUCT query for each named graph via [t-mustache](https://github.com/linkedpipes/etl/tree/master/plugins/t-mustache), pass that query to e-sparqlEndpoint. However, there are at least two problems with this approach. First, passing multiple configurations is not generally supported by LP-ETL's components, so we may encounter a similar issue to linkedpipes/etl#176. Second, we need to coordinate the configuration of the extractor (i.e. e-sparqlEndpoint) and the loader (i.e. l-graphStoreProtocol), so that the original named graphs and the target named graphs are not mixed. This could be possibly solved by materializing the graph name in its data via the generated CONSTRUCT query. The named graph can be then picked out from the e-sparqlEndpoint's output and transformed into configuration for l-graphStoreProtocol. However, since LP-ETL does not support working with multiple RDF units passed via one edge (they need to be merged by t-graphMerger), this solution would not work. Instead of redesigning LP-ETL to support multiple RDF units passed via a single edge, this functionality may be wrapped in a component.

Once bulk synchronization is resolved we can investigate the options for limiting the needless overwrites of data by synchronizing only the changed data. The [SPARQL Graph Store protocol](https://www.w3.org/TR/sparql11-http-rdf-update/#http-head) suggests that requesting a named graph via the `HEAD` request can provide a response with the `Last-Modified` HTTP header indicating the time of the last change. Unfortunately, this header is not provided by Fuseki at the moment (see [this issue](https://issues.apache.org/jira/browse/JENA-388)).

Instead, we could resort to tracking the last modified dates via [e-dcatAp11Dataset](https://github.com/linkedpipes/etl/tree/master/plugins/e-dcatAp11Dataset). This component allows to specify the last modified date as part of the dataset's metadata. Using this component the last modified date can be represented as follows:

``` turtle
@prefix : <http://example.com/> .
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

:dataset a dcat:Dataset ;
  dcterms:modified "2016-07-07"^^xsd:date .
```

However, this solution requires a disciplined manual intervention updating the last modified date in e-dcatAp11Dataset if before a pipeline is run.

An automated alternative that can work is to use checksums to detect if the content of a named graph has changed. For example, we can group and concatenate all literals per named graph and compute a SHA1 hash from them:

``` sparql
SELECT ?g (SHA1(GROUP_CONCAT(STR(?literal); separator = "")) AS ?checksum)
WHERE {
  GRAPH ?g {
    [] ?p ?literal .
    FILTER isLiteral(?literal)
  }
}
GROUP BY ?g
```

If a different hash for a named graph is computed than the hash computed previously (and persisted in the staging store), the named graph can be synchronized and its hash updated. Nevertheless, the hashing may be prohibitively expensive operation especially when using larger datasets. It also does not account for the cases when RDF resources or their relationships are changed instead of literals.

In either case, we would need to record the date of the last synchronization into the staging store, so that we can select named graphs that changed since the last synchronization was run.

We would also need to decide on the level of granularity at which we perform the synchronization. The solution using the `Last-Modified` header works on the level of named graphs. The solution using the explicit metadata produced by e-dcatAp11Dataset works on the level of dataset. Datasets can correspond one-to-one to named graphs, if we establish and follow this as a convention (also discussed in openbudgets/datasets#24). In theory, we could also consider other levels of granularity, such as individual RDF triples, but that would become unwieldy.

**Comment by schmaluk** [comment]
Assuming that it is still valid to have 2 separate triplestores, since otherwise having just 1 would be easier to deal with.
@jindrichmynarz @marek-dudas @jakubklimek  Would someone of UEP provide me such a synchronisation between the triplestores, which I can then integrate? Can also establish a regular triggering of sthg running as a cronjob, if needed.

**Comment by jindrichmynarz** [comment]
Sure, having two separate triple stores is valid. However, as I indicated in my comment, the synchronization is non-trivial. It would be great to hear from @jakubklimek on this topic.

**Comment by jakubklimek** [comment]
Instead of going into the technical details, which can always be sorted out and do not concern most of the partners (we have a similar setup with staging and production triplestores and "publication" pipelines internally), I think we should instead address the issue of the intended data workflow. The purpose of the staging triplestore is to provide a place where data can be processed before publication. This may include e.g. linking via Alignment and possibly other manual or semi-automatic steps. Therefore, this "publication" from staging to production triplestores may not be automated. These are all things that should be answered before we go into technical details of how to actually publish the data.

**Comment by jindrichmynarz** [comment]
Yes, we discussed the need for filtering data in the last tech call. However, we agreed to start with simply pushing everything and then progressively improve the synchronization.

**Comment by jakubklimek** [comment]
If no manual steps are to be done now, it is just about cloning the Fuseki instance. This can be done outside of LP-ETL (and it is also the fastest way) by simply copying the Fuseki files once in a while.

**Comment by jindrichmynarz** [comment]
So you would suggest to implement this as a cron-job that stops the production instance of Fuseki, deletes its database files, SCPs the database files of the staging instance in place, and restarts the production instance? Are the Fuseki database files transferable between servers?

**Comment by jakubklimek** [comment]
Seems to me as the easiest thing to do if we want a 1:1 copy. The files are transferable like this, if the configuration is similar.

**Comment by jindrichmynarz** [comment]
Looking at the [Docker configuration for Fuseki](https://github.com/openbudgets/integration/tree/master/docker-config/fuseki) it seems we use a single configuration file for Fuseki. @mlukasch, can you create the cron-job discussed above?

**Comment by schmaluk** [comment]
Yes I think I can do this.

**Comment by schmaluk** [comment]
Should be done but not yet deployed. Atm every 15 minutes data is synced 1:1 from staging to production. Whatever is in production will be overwritten by staging. Syncing also includes restart of fuseki production.

**Comment by HimmelStein** [comment]
It would be good that we first settle down the difference between staging and production.

In yesterday's discussion, there are two differences between staging and production: (1) staging is used for testing -- ETL developers first transfer RDF graphs into staging and testing (including quality testing). When everything goes well, then these RDF graphs will be transferred into production. (2) staging = production.  
Personally, I prefer to (1), in part because of my experience with the early versions of the FDP2RDF pipeline. Staging = production reminds me something like 'backup', which needs regular synchronizing, which would be another topic of the platform.  

What do you think?

**Comment by jindrichmynarz** [comment]
@mlukasch, how long does the syncing take? How much data, in terms of RDF triples, does it currently sync? I think syncing every 15 minutes may be too frequent.

@HimmelStein, I think we agreed that we want to achieve (1), but we start with (2) for the simplicity's sake, and then gradually build the synchronization towards (1).

**Comment by HimmelStein** [comment]
@jindrichmynarz Let us discuss this issue concretely. (init) both staging and production are empty; (one day) staging has one graph, containing inconsistency, while production is empty; (next day) production is synchronized, containing the same graph as the staging; (third day) the inconsistency in the staging is corrected, and new graphs with inconsistency are added; (fourth day) production is synchronized, with the first graph (with improved consistency) and new inconsistent graphs. ... Then, the production is always containing no less (normally more) of inconsistency than that in the staging. Is there something incorrect above? or should the synchronization be manually and selectively triggered?  nice weekend.

**Comment by jindrichmynarz** [comment]
I think we can simply say that with the current solution of synchronization the data in the staging and production environments becomes eventually (in 15 minutes) the same. If there is inconsistent data, both staging and production environment have it.

If we want to improve this way of synchronization, we should first answer what data is pushed to production and then we can discuss how to implement the improved synchronization. One answer to that question is that we push (or retract) data that (1) has changed (i.e. was created, updated, deleted) and (2) passes the clearance pipeline.

**Comment by pwalsh** [comment]
@badmotor I'm closing this. It must be out of date, and any specific issues can be raised with distinct issues.
