### ISSUE TITLE
os-packager showing status of transformation to RDF does not work

### ISSUE THREAD

**Issue by marek-dudas** [openbudgets/platform#68]
The status check of the FDPtoRDF pipeline in http://apps.openbudgets.eu/packager seems not working. When tested in Chrome, it keeps getting the following error:
```
XMLHttpRequest cannot load https://crossorigin.me/http://apps.openbudgets.eu/linkedpipes/test/resources/executions/ce6401d6-bdd8-4652-9aa7-0c47e79b581f/overview. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://apps.openbudgets.eu' is therefore not allowed access. The response had HTTP status code 522.
```
Why is it dealing with crossorigin anyway? Both the packager and the linkedpipes are on the same domain.
The dataset is transformed and available in viewer, so those parts work.

@pierorex or whoever is available, could you look into this?

**Comment by pierorex** [comment]
I was getting CORS errors when coding that part because the linkedpipes app was not in my machine, the crossorigin proxy allowed me to get through that issue back then and I forgot to remove it.
It was working well until now because it didn't do anything to block the request, but now crossorigin.me is down and that's why we're getting the error.
I will look into that now and see make it work, thank you @marek-dudas :)

**Comment by pierorex** [comment]
Solved with https://github.com/openbudgets/os-packager/commit/3ba767362ff4681ca264406f64180e46239cb452
