### ISSUE TITLE
Saving the transformed RDF-datasets to the filesystem

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#7]
After the fdp-data has been transformed to the rdf-format, we need to **store the converted rdf-datasets somewhere on the filesystem** on the Server.

Please extend the Pipeline to store the data after Transformation on the filesystem.
(@mlukasch will do the configuration: filesystem Location, etc.)

**Comment by jindrichmynarz** [comment]
I think this can be easily resolved by as an issue at [openbudgets/pipeline-fragments](https://github.com/openbudgets/pipeline-fragments) by @marek-dudas together with the other issues. It should suffice to extend the FDP2RDF pipeline with [l-filesToScp](https://github.com/linkedpipes/etl/tree/master/plugins/l-filesToScp) that loads the RDF dump of the pipeline's result to a specified location on file system.

@mlukasch, you can then create a user that would be authorized to write to a specified location on file system. The access credentials for this user will be then provided by you into the pipeline. Optionally, the location where the RDF dumps will be stored can be served via an HTTP server, so that we can make the data publicly available.

**Comment by schmaluk** [comment]
Sounds great. @marek-dudas can you please integrate this in the pipeline when you have time for this. Will do the config as described. Thanks a lot.

**Comment by marek-dudas** [comment]
Sure. Just one question: if the goal is to store the data on the same server where LinkedPipes are running, it might be easier to just use [l-filestolocal](http://etl.linkedpipes.com/components/l-filestolocal) component, which needs just the filepath as configuration. But then the user running LinkedPipes would have to have write access to the destination folder. Maybe I can add both I-filestolocal and I-filesToScp to the pipeline and you will disable the one that is less convenient (that is a one-click action in the linkedpipes UI). The other one might be useful in the future anyway.

**Comment by pwalsh** [comment]
keep in mind that linkedpipes is running here in a docker container, so if a local filestore is being used, steps need to be taken to ensure it is persistent.

**Comment by jakubklimek** [comment]
I would advise against using the local storage components in production environment. They are meant mainly for debugging on local developer machines as they unnecessarily tie the storage to the same server as the LP-ETL is running on, which may change later. Using remote storage is a much better option.

**Comment by marek-dudas** [comment]
Ok, I added the I-filesToScp component to the pipeline, it is now on github together with updated documentation.

**Comment by schmaluk** [comment]
Thanks for the help. The pipeline is added & configured on the Server.
