### ISSUE TITLE
Uploading the converted rdf-datasets to the OS-filestorage

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#8]
Once the fdp-datasets have been transformed to rdf and saved somewhere on the Server (https://github.com/openbudgets/platform/issues/7), we need to **upload the rdf-datasets to the OS-filestorage.**

Therefore we Need an **API in OpenSpending for uploading datasets** to their filestorage, which can be integrated into the Pipeline as well.

Lets discuss here, which of their existing APIs is suitable to be used in the Pipeline.

**Comment by pwalsh** [comment]
@mlukasch 

First we need to understand exactly what we are uploading. As discussed in tech call yesterday, I though we were uploading the whole dataset as RDF. @jindrichmynarz made comments that indicate I may be wrong, and that we only need metadata, which will point to a uri for the data (presumably, via the http proxy you have configured on nginx). If indeed it is just metadata, then I suggest we use https://datahub.io and I'll create an openbudgets namespace there (this is a public CKAN instance that OKI commits to keeping up)

**Comment by jindrichmynarz** [comment]
What we at UEP have been doing is upload data dumps to a file system using [l-filesToScp](https://github.com/linkedpipes/etl/tree/master/plugins/l-filesToScp). The part of the file system we push the dumps to is exposed via an HTTP server, which gives us a URL for each dump. We refer to these URLs in metadata generated by [e-distributionMetadata](https://github.com/linkedpipes/etl/tree/master/plugins/e-distributionMetadata) and pushed to CKAN via [l-dcatApToCkan](https://github.com/linkedpipes/etl/tree/master/plugins/l-dcatApToCkan).

This is merely one of the options for storing data dumps. An alternative to this setup is to push dumps to CKAN's [FileStore](http://docs.ckan.org/en/latest/maintaining/filestore.html) instead of a file system managed by an HTTP server. Similarly, we can replace it with pushing the dumps into the [OpenSpending Datastore](http://openspending.readthedocs.io/en/master/developers/datastore/).

The option we adopt should reflect the needs we need to address. For example, the setup with CKAN requires more effort, but CKAN gives us better overview of the datasets we have. Before we decide which option to adopt we should consider the requirements of the applications that consume OpenBudgets.eu data.

If we simply need to persist data dumps somehow, the easiest option is to use l-filesToScp and load to a file system.

**Comment by schmaluk** [comment]
Beside the datamining Im not aware so far of any application in the OBEU stack consuming rdf data outside the triplestores. If this is the case, it is maybe the best to include the datamining ppl to the discussion. And they can decide which Solution fits best for them and their applications.

**Comment by jindrichmynarz** [comment]
I agree that the decision should be based on the input of the data consumers.

I think simplest solution might be to publicly expose the data dumps via HTTP. The consumers can then use any HTTP client to obtain the data they need, without needing to use a special library. At the moment I don't see any reason not to expose the data publicly, so this solution might be fine.

**Comment by schmaluk** [comment]
If there is no demand for another solution, I would actually prefer pushing the dumps to the OS Datastore or somewhere else in the cloud, since this seems to me more like a Long-term solution. Storage on the Server@Fhg will always be limited (atm 1 TB) and wont scale automatically.

**Comment by jindrichmynarz** [comment]
Sure, that is also an option. Perhaps we can discuss this in the next tech call so that our internal consumers (@propi, @vojir, @jaroslav-kuchar et al.) of the OpenBudgets.eu data can have their say.

**Comment by schmaluk** [comment]
Hi everyone, as discussed in the today's Meeting, FDP-files hitting the endpoint at http://eis-openbudgets.iais.fraunhofer.de/linkedpipes/execute/fdp2rdf, getting transformed & their dump are exposed here: http://eis-openbudgets.iais.fraunhofer.de/dumps/
